defaults:
  - hydra: default
  - env: default
  - log: default

worker: main_lmim
output_dir: ./checkpoints
job_name: latentMIM_csi
dataset: csi_cdla
data_path: data_gen/csi_cdla

encoder: vit_tiny
in_chans: 1
patch_size: 4
decoder_depth: 3
target_depth: 12
target_mom: 0.99
target_update_freq: 1
loss: infonce_patches
tau: 0.2
use_proj: False

drop: 0.
attn_drop: 0.
drop_path: 0.

input_size: 64
min_crop: 1.0
grid_size: 16
num_vis: 25
patch_gap: 0
avg_vis_mask_token: True
avg_sim_coeff: 0.1
sim_init: 0.75
sim_end: 0.25
mask_target: True
freeze_pe: True

proj:
  mlp_dim: 4096
  mlp_depth: 3

epochs: 200
warmup_epochs: 20
start_epoch: 0
batch_size: 128
weight_decay: 0.05
blr: 1.5e-4
accum_iter: 1
lr:
min_lr_frac: 0.25
resume: True

knn_eval_only: False
eval_freq: 10

log:
  print_freq: 547
  save_freq: 20
  use_wandb: False
